#pragma once

#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "raft/kv_command.h"
#include "raft/raft_node.h"
#include "raft/state_machine.h"

namespace distributed_kv::storage {
class KVStore;
}

namespace distributed_kv::raft {

enum class SubmitStatus {
  kNotLeader,
  kPending,
  kApplied,
  kInvalid,
};

struct SubmitResult {
  SubmitStatus status{SubmitStatus::kInvalid};
  LogIndex log_index{0};
  std::optional<ApplyResult> result;
  std::vector<OutboundRpc> outbound;
};

/**
 * Composes RaftNode with the replicated KV StateMachine.
 *
 * The service remains deterministic and single-threaded. It tracks locally
 * submitted log indexes so a transport layer can wait for commit completion.
 */
class RaftKVService final {
 public:
  /**
   * Creates a recovered service over a KVStore that outlives it.
   *
   * Input: Raft configuration, non-owning KVStore/persistence, and optional
   * snapshot whose boundary must match the durable committed log.
   * Output: snapshot-restored service with committed suffix replayed.
   * Thread safety: construction requires exclusive access.
   */
  RaftKVService(NodeConfig config, storage::KVStore& store,
                RaftPersistence* persistence = nullptr,
                const StateMachineSnapshot* snapshot = nullptr);

  RaftKVService(const RaftKVService&) = delete;
  RaftKVService& operator=(const RaftKVService&) = delete;
  RaftKVService(RaftKVService&&) = delete;
  RaftKVService& operator=(RaftKVService&&) = delete;

  /**
   * Advances Raft logical time.
   *
   * Input: elapsed monotonic milliseconds and writable application error.
   * Output: election or heartbeat RPCs.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::vector<OutboundRpc> tick(std::uint64_t elapsed_ms,
                                              std::string& error);

  /**
   * Delegates RequestVote request handling.
   *
   * Input: request.
   * Output: vote response.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] RequestVoteResponse handleRequestVote(
      const RequestVoteRequest& request);

  /**
   * Delegates one RequestVote response.
   *
   * Input: responding peer, response, and writable application error.
   * Output: RPCs generated by a possible leadership transition.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::vector<OutboundRpc> handleRequestVoteResponse(
      NodeId source, const RequestVoteResponse& response,
      std::string& error);

  /**
   * Handles AppendEntries and applies newly committed follower entries.
   *
   * Input: request and writable fatal application error.
   * Output: append response; error remains empty on healthy processing.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] AppendEntriesResponse handleAppendEntries(
      const AppendEntriesRequest& request, std::string& error);

  /**
   * Handles a replication response and applies newly committed Leader entries.
   *
   * Input: responding peer, response, and writable fatal error.
   * Output: retry/next-batch RPCs.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::vector<OutboundRpc> handleAppendEntriesResponse(
      NodeId source, const AppendEntriesResponse& response,
      std::string& error);

  /**
   * Encodes and proposes one SET/DELETE command on the Leader.
   *
   * Input: validated command fields and writable error.
   * Output: not-leader, pending, applied, or invalid result plus RPCs.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] SubmitResult submit(const KVCommand& command,
                                    std::string& error);

  /**
   * Removes one completed local request result by log index.
   *
   * Input: originally returned pending index.
   * Output: committed state-machine result when available.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::optional<ApplyResult> takeResult(LogIndex index);

  /**
   * Reads already-applied local state without performing a Raft read barrier.
   *
   * Input: key.
   * Output: copied local value or std::nullopt.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::optional<std::string> getApplied(
      const std::string& key) const;

  /**
   * Exposes immutable consensus state for transport and tests.
   *
   * Input: none.
   * Output: borrowed RaftNode reference.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] const RaftNode& raftNode() const noexcept;

  /**
   * Exposes the highest applied state-machine index.
   *
   * Input: none.
   * Output: lastApplied.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] LogIndex lastApplied() const noexcept;

 private:
  /**
   * Applies every newly committed entry in strict order.
   *
   * Input: writable fatal error.
   * Output: true when state machine catches up to commitIndex.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] bool applyCommitted(std::string& error);

  RaftNode raft_node_;
  StateMachine state_machine_;
  std::unordered_set<LogIndex> pending_local_;
  std::unordered_map<LogIndex, ApplyResult> completed_local_;
};

}  // namespace distributed_kv::raft
