#pragma once

#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "raft/file_snapshot_store.h"
#include "raft/kv_command.h"
#include "raft/raft_node.h"
#include "raft/state_machine.h"

namespace distributed_kv::storage {
class KVStore;
}

namespace distributed_kv::raft {

enum class SubmitStatus {
  kNotLeader,
  kPending,
  kApplied,
  kInvalid,
};

struct SubmitResult {
  SubmitStatus status{SubmitStatus::kInvalid};
  LogIndex log_index{0};
  std::optional<ApplyResult> result;
  std::vector<OutboundRpc> outbound;
};

struct SnapshotPublishResult {
  bool performed{false};
  LogIndex boundary_index{0};
  Term boundary_term{0};
};

/**
 * Composes RaftNode with the replicated KV StateMachine.
 *
 * The service remains deterministic and single-threaded. It tracks locally
 * submitted log indexes so a transport layer can wait for commit completion.
 */
class RaftKVService final {
 public:
  /**
   * Creates a recovered service over a KVStore that outlives it.
   *
   * Input: Raft configuration, non-owning KVStore/persistence, and optional
   * snapshot whose boundary must match the durable committed log.
   * Output: snapshot-restored service with committed suffix replayed.
   * Thread safety: construction requires exclusive access.
   */
  RaftKVService(NodeConfig config, storage::KVStore& store,
                RaftPersistence* persistence = nullptr,
                const StateMachineSnapshot* snapshot = nullptr,
                FileSnapshotStore* snapshot_store = nullptr);

  RaftKVService(const RaftKVService&) = delete;
  RaftKVService& operator=(const RaftKVService&) = delete;
  RaftKVService(RaftKVService&&) = delete;
  RaftKVService& operator=(RaftKVService&&) = delete;

  /**
   * Advances Raft logical time.
   *
   * Input: elapsed monotonic milliseconds and writable application error.
   * Output: election or heartbeat RPCs.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::vector<OutboundRpc> tick(std::uint64_t elapsed_ms,
                                              std::string& error);

  /**
   * Delegates RequestVote request handling.
   *
   * Input: request.
   * Output: vote response.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] RequestVoteResponse handleRequestVote(
      const RequestVoteRequest& request);

  /**
   * Delegates one RequestVote response.
   *
   * Input: responding peer, response, and writable application error.
   * Output: RPCs generated by a possible leadership transition.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::vector<OutboundRpc> handleRequestVoteResponse(
      NodeId source, const RequestVoteResponse& response,
      std::string& error);

  /**
   * Handles AppendEntries and applies newly committed follower entries.
   *
   * Input: request and writable fatal application error.
   * Output: append response; error remains empty on healthy processing.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] AppendEntriesResponse handleAppendEntries(
      const AppendEntriesRequest& request, std::string& error);

  /**
   * Handles a replication response and applies newly committed Leader entries.
   *
   * Input: responding peer, response, and writable fatal error.
   * Output: retry/next-batch RPCs.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::vector<OutboundRpc> handleAppendEntriesResponse(
      NodeId source, const AppendEntriesResponse& response,
      std::string& error);

  /**
   * Encodes and proposes one SET/DELETE command on the Leader.
   *
   * Input: validated command fields and writable error.
   * Output: not-leader, pending, applied, or invalid result plus RPCs.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] SubmitResult submit(const KVCommand& command,
                                    std::string& error);

  [[nodiscard]] ProposeResult proposeConfChange(ConfChangeType type,
                                                 ClusterMember member,
                                                 std::uint64_t operation_id = 0);

  [[nodiscard]] bool addLearner(NodeId learner_id);
  [[nodiscard]] bool learnerCaughtUp(NodeId learner_id) const noexcept;

  /**
   * Removes one completed local request result by log index.
   *
   * Input: originally returned pending index.
   * Output: committed state-machine result when available.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::optional<ApplyResult> takeResult(LogIndex index);

  /**
   * Reads already-applied local state without performing a Raft read barrier.
   *
   * Input: key.
   * Output: copied local value or std::nullopt.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] std::optional<std::string> getApplied(
      const std::string& key) const;

  /**
   * Exposes immutable consensus state for transport and tests.
   *
   * Input: none.
   * Output: borrowed RaftNode reference.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] const RaftNode& raftNode() const noexcept;

  /**
   * Exposes the highest applied state-machine index.
   *
   * Input: none.
   * Output: lastApplied.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] LogIndex lastApplied() const noexcept;

  /**
   * Publishes a state snapshot and compacts the durable Raft journal prefix.
   *
   * Input: snapshot store, minimum applied entries since the last publication,
   * and writable error. Output: result describing whether publication occurred.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] bool tryPublishSnapshot(
      FileSnapshotStore& store, std::size_t entry_threshold,
      SnapshotPublishResult& result, std::string& error);

  /**
   * Returns the last included index from startup or the latest publication.
   *
   * Input: none. Output: snapshot boundary index.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] LogIndex lastSnapshotIndex() const noexcept;

  /**
   * Handles one InstallSnapshot chunk on a follower.
   */
  [[nodiscard]] InstallSnapshotResponse handleInstallSnapshot(
      const InstallSnapshotRequest& request, FileSnapshotStore& store,
      std::string& error);

  /**
   * Processes one InstallSnapshot response on the Leader.
   */
  [[nodiscard]] std::vector<OutboundRpc> handleInstallSnapshotResponse(
      NodeId source, const InstallSnapshotResponse& response,
      FileSnapshotStore& store, std::string& error);

 private:
  struct LeaderSnapshotSend {
    LogIndex last_included_index{0};
    Term last_included_term{0};
    std::uint64_t offset{0};
  };

  [[nodiscard]] std::vector<OutboundRpc> completeReplication(
      std::vector<OutboundRpc> outbound, FileSnapshotStore& store,
      std::string& error);

  [[nodiscard]] std::optional<OutboundRpc> makeInstallSnapshotRpc(
      NodeId peer, FileSnapshotStore& store, std::string& error);

  [[nodiscard]] std::vector<OutboundRpc> finalizeOutbound(
      std::vector<OutboundRpc> outbound, std::string& error);

  /**
   * Applies every newly committed entry in strict order.
   *
   * Input: writable fatal error.
   * Output: true when state machine catches up to commitIndex.
   * Thread safety: owning service event thread only.
   */
  [[nodiscard]] bool applyCommitted(std::string& error);

  RaftNode raft_node_;
  StateMachine state_machine_;
  std::unordered_set<LogIndex> pending_local_;
  std::unordered_map<LogIndex, ApplyResult> completed_local_;
  LogIndex last_snapshot_index_{0};
  FileSnapshotStore* snapshot_store_{nullptr};
  std::unordered_map<NodeId, LeaderSnapshotSend> snapshot_sends_;
  std::optional<SnapshotFileReceiver> snapshot_receiver_;
};

}  // namespace distributed_kv::raft
